package com.example.myapp.ui.note

import android.app.Application
import androidx.lifecycle.*
import com.example.myapp.data.NoteRepository
import com.example.myapp.data.local.NoteDatabase
import com.example.myapp.data.model.Note
import kotlinx.coroutines.launch

class NoteViewModel(
    application: Application,
) : AndroidViewModel(application) {

    private val repository: NoteRepository = NoteRepository(NoteDatabase.getDatabase(application).noteDao())
    private val _currentNote = MutableLiveData<Note?>()
    val currentNote: LiveData<Note?> = _currentNote

    // Store the noteId from navigation arguments
    var noteId: Int? = /*savedStateHandle.get<Int>("noteId")?.takeIf { it != -1 }*/1

    init {
        noteId?.let {
            viewModelScope.launch {
                repository.getNoteById(it).collect { note ->
                    _currentNote.postValue(note)
                }
            }
        }
    }

    // loadNote is primarily triggered by noteId in init.
    // This explicit loadNote can be used if needed, but might be redundant.
    fun loadNoteById(id: Int): LiveData<Note?> {
        val liveData = MutableLiveData<Note?>()
        viewModelScope.launch {
            repository.getNoteById(id).collect{ note ->
                liveData.postValue(note)
                if (id == this@NoteViewModel.noteId) { // If loading the primary note for this VM instance
                    _currentNote.postValue(note)
                }
            }
        }
        return liveData
    }

    fun saveNote(name: String, content: String) {
        viewModelScope.launch {
            val currentLoadedNote = _currentNote.value // Use the note loaded via noteId
            if (currentLoadedNote != null && currentLoadedNote.noteId == noteId && noteId != null) {
                // Update existing note being edited
                val updatedNote = currentLoadedNote.copy(
                    name = name,
                    content = content,
                    lastModifiedDate = System.currentTimeMillis()
                )
                repository.updateNote(updatedNote)
            } else {
                // Create new note (noteId was null or didn't match _currentNote)
                // Or if noteId was for a different note than what was in _currentNote (edge case)
                val newNote = Note(
                    name = name,
                    content = content,
                    lastModifiedDate = System.currentTimeMillis()
                    // noteId will be auto-generated by Room if 0, or use existing if it's an update of a different note
                )
                repository.insertNote(newNote)
            }
        }
    }
}
